- name: download and extract the specified version
  become: yes
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kubernetes.version }}/bin/linux/amd64/kube-proxy"
    dest: /usr/local/bin/

- name: make sure it's executable
  become: yes
  file:
    path: /usr/local/bin/kube-proxy
    mode: "u+rwx"

- name: restart the service
  become: yes
  service:
    name: kube-proxy
    state: restarted
